### PR TITLE
Create Enemy generator

### PR DESCRIPTION
**Pull request by FabianByrne**
The current enemy generator. Using the "player_data.txt" and "game_data.txt" files, it creates then opens a JSON file called "enemy_data.txt" with the generated enemy's stats.

### CODE REVIEW

**Review by GAMarchbank — CHANGES_REQUESTED** [review]
hey fabian mate, 
really good work, 

just a couple of changes before merging, 

first can you move the parts of the code where it loads the player's level, location and the enermy attacks and personality types to within the function, 
means the other people wont have to enter them as arguements, limiting things that can be entered incorrectly. 

secondly can you double_check the key names in the enermies dictionary, 
i think they dont match the ones in the example list on the battle sim, 

ill copy the list here for reference. 

make these changes and we are ready for merger

{"name": "Scorpion", "level": 2, "Location": "Desert", "items": ['great vibes'], "hp": 7, "a_p": 2, "d_p": 2, 's_p': 10, 'aim': 20, "attacks": ['Scratch'], 'personality': 'wild')

**Comment by FabianByrne** [comment]
Well spotted, i'll make the changes. By the way, I noticed there is a capital letter on "Location" in that example you've pasted in. Might cause problems later

**Review by GAMarchbank — COMMENTED** [review]
sent my comments on wattapp, 
we are so near i can taste it

**Review by GAMarchbank — APPROVED** [review]
mate this is it.

woot

**Pull request merged**
